
services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./docker/php/Dockerfile
    dockerContext: .
    buildCommand: "composer install && npm install && npm run build"
    startCommand: "php artisan serve --host=0.0.0.0 --port=8000"
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mongodb
      - key: MONGODB_URL
        value: mongodb+srv://montanoarboleda1:7ie2VT5IHE1zI36x@cluster0.rb7fm.mongodb.net/User_LaravelFirst?retryWrites=true&w=majority&appName=Cluster0
         

